config/routes.rb
Rails.application.routes.draw do

  root "homes#top"
  get "about" => "homes#about"

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :users, except: [:create, :new] do
    get "unsubscribe/:id" => "users#unsubscribe", as: "unsubscribe"
    collection do
      get "search"
    end
  end

  devise_scope :user do
    get "signup" => "users/registrations#new"
    get "login" => "users/sessions#new"
    delete "logout" => "users/sessions#destroy"
    post "guest_sign_in" => "users/sessions#guest_sign_in"
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get "followings/:id", :to => "relationships#followings", as: "followings"
  get "followers/:id", :to => "relationships#followers", as: "followers"

  resources :posts do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only:[:create, :destroy]
    get "delete_confirm/:id" => "posts#delete_confirm", as: "delete_confirm"
    collection do
      get "search"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image_id, UserImageUploader

  has_many :posts, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  has_many :post_comments

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  validates :name, presence: true, uniqueness: true, length: { in: 1..20 }
  validates :email, presence: true, uniqueness: true

  def self.guest
    find_or_create_by!(name: "guest-user", email: "guest@ituka.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: "ゲストユーザーとしてログインしました。"
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_normal_user, only: [:update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :unsubscribe, :destroy,]

  def index
    @users = User.all.page(params[:page]).per(16)
  end

  def show
    @posts = @user.posts.page(params[:page]).per(9)
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user.id), notice: "ユーザー情報を更新しました。"
  end

  def unsubscribe
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: "退会処理が完了しました。"
  end

  def search
    if params[:keyword].present?
      @users = User.where('name LIKE ?', "%#{params[:keyword]}%").page(params[:page])
      @keyword = params[:keyword]
    else
      @users = User.all.page(params[:page])
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_normal_user
    if current_user.email == "guest@ituka.com"
      redirect_to posts_path, notice: "ゲストユーザーの更新・削除はできません。"
    end
  end

  def user_params
    params.require(:user).permit(:image_id, :name, :email, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <%= form_with model: @user, url: user_path(@user.id), local: true do |f| %>
    <div class="row">
      <div class="col-md-6 mt-4">
        <div class="field">
          <%= f.file_field :image_id, class: "img-field", style: "display:none" %>
        </div>
        <%= image_tag @user.image_id.url, onClick: "$('.img-field').click()", class: "img-thumbnail img-prev" %>
      </div>
      <div class="col-md-6 pt-3">
        <div class="field">
          <span class="table-head"><%= f.label :name, "◯ニックネーム" %></span>
          <br />
          <%= f.text_field :name, size: "40px" %>
        </div>
        <div class="field mt-3">
          <span class="table-head"><%= f.label :email, "◯メールアドレス" %></span>
          <br />
          <%= f.email_field :email, size: "56px" %>
        </div>
        <div class="field mt-3">
          <span class="table-head"><%= f.label :introduction, "◯自己紹介文" %></span>
          <br />
          <%= f.text_area :introduction, size: "55x4" %>
        </div>
        <div class="actions text-right mr-4 mt-4">
          <%= f.submit "更新する", class: "btn btn-success btn-sm px-3" %>
          <%= link_to "退会する", user_unsubscribe_path(@user.id), class: "btn btn-danger btn-sm px-3 ml-4" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <%= render "layouts/user_search_form" %>
      <div class="col-md-12 mb-3">
        <h2>Users</h2>
      </div>
    <%= render "layouts/users_left", users: @users %>
    <% if @users.count > 8 %>
      <%= render "layouts/center_line" %>
      <%= render "layouts/users_right", users: @users %>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<div class="container">
  <div class="row">
    <%= render "layouts/user_search_form" %>
      <div class="col-md-12">
        <h5>検索結果 "<strong><%= @keyword %></strong>"</h5>
      </div>
    <%= render "layouts/users_left", users: @users %>
    <% if @users.count > 8 %>
      <%= render "layouts/users_right", users: @users %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">
      <h2>Profile</h2>
      <%= image_tag @user.image_id.url, class: "img-thumbnail" %><br />
      <p></p>
      <table width="90%">
        <tr class="profile">
          <td class="col-md-5 col-sm-5">ニックネーム</td>
          <td><%= @user.name %></td>
        </tr>
        <tr class="profile">
          <td class="col-md-5 col-sm-5">自己紹介</td>
          <td><%= @user.introduction %></td>
        </tr>
        <tr class="profile">
          <td class="col-md-5 col-sm-5">フォロー</td>
          <td class="follow-border">
            <%= link_to followings_path, class: "link following" do %>
              <%= @user.following_user.count %>
            <% end %>
            人
          </td>
        </tr>
        <tr class="profile">
          <td class="col-md-5 col-sm-5">フォロワー</td>
          <td class="follow-border">
            <%= link_to followers_path, class: "link follower" do %>
              <%= @user.follower_user.count %>
            <% end %>
            人
          </td>
        </tr>
      </table>
      <% if @user == current_user %>
        <div class="text-right mr-5 pr-2 mt-3">
          <%= link_to "編集する", edit_user_path(@user.id), class: "btn btn-primary btn-sm px-3" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-7">
      <h2>Post's list</h2>
        <% @user.posts.reverse.each do |post| %>
          <div class="user-posts">
            <%= link_to post_path(post.id) do %>
              <%= image_tag post.image_id.url, size: "200x160" %>
            <% end %>
          </div>
        <% end %>
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center mt-5">
      <i class="fas fa-exclamation-triangle fa-7x"></i>
      <h2 class="mt-4 mb-4">退会手続きの前にご確認ください</h2>
      <div class="d-flex justify-content-center">
        <p class="confirm-text mb-5">
          退会すると投稿履歴が全て削除されます。<br />
          本当によろしいですか？
        </p>
      </div>
      <%= link_to "退会する", user_path(@user.id), method: :delete, class: "btn btn-outline-danger btn-sm px-3" %>
      <%= link_to "戻る", user_path(@user.id), class: "btn btn-outline-primary btn-sm px-4 ml-5" %>
    </div>
  </div>
</div>