config/routes.rb
Rails.application.routes.draw do

  root "homes#top"
  get "about" => "homes#about"

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :users, except: [:create, :new] do
    get "unsubscribe/:id" => "users#unsubscribe", as: "unsubscribe"
    collection do
      get "search"
    end
  end

  devise_scope :user do
    get "signup" => "users/registrations#new"
    get "login" => "users/sessions#new"
    delete "logout" => "users/sessions#destroy"
    post "guest_sign_in" => "users/sessions#guest_sign_in"
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get "followings/:id", :to => "relationships#followings", as: "followings"
  get "followers/:id", :to => "relationships#followers", as: "followers"

  resources :posts do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only:[:create, :destroy]
    get "delete_confirm/:id" => "posts#delete_confirm", as: "delete_confirm"
    collection do
      get "search"
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord

  mount_uploader :image_id, PostImageUploader

  belongs_to :user
  has_many :post_comments
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  validates :title, presence: true, length: { in: 1..20 }

  # 既にいいねしているか確認するメソッド
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :delete_confirm, :destroy]

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post.id), notice: "投稿しました。"
    else
      redirect_to new_post_path
      flash[:no_post] = "※Titleを入力してください。"
    end
  end

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all.page(params[:page]).per(28)
  end

  def show
    @user = @post.user
    @favorite = Favorite.new
    @post_comments = @post.post_comments
    @post_comment = PostComment.new
  end

  def edit
  end

  def update
    @post.update(post_params)
    redirect_to post_path(@post.id), notice: "投稿内容を更新しました。"
  end

  def delete_confirm
  end

  def destroy
    @post.destroy
    redirect_to user_path(@post.user.id), notice: "投稿を削除しました。"
  end

  def search
    if params[:keyword].present?
      @posts = Post.where('title LIKE ?', "%#{params[:keyword]}%").or(Post.where('country LIKE ?', "%#{params[:keyword]}%")).page(params[:page]).per(28)
      @keyword = params[:keyword]
    else
      @posts = Post.all.page(params[:page]).per(28)
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :image_id, :country, :text)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/delete_confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 my-5 py-4"></div>
    <div class="col-md-12 text-center">
      <h2>本当にこの投稿を削除してよろしいですか？</h2>
    </div>
    <div class="col-12 d-flex justify-content-center mt-5">
      <table>
        <tr>
          <td><%= link_to "削除する", post_path(@post.id), method: :delete, class: "btn btn-danger btn-sm mr-4" %></td>
          <td><%= link_to "戻る", post_path(@post.id), class: "btn btn-primary btn-sm px-4" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <%= form_with model: @post, url: post_path(@post.id), local: true do |f| %>
    <div class="row">
      <div class="col-md-6 mt-4">
        <div class="field">
          <%= f.file_field :image_id, class: "img-field", style: "display:none" %>
        </div>
        <%= image_tag @post.image_id.url, onClick: "$('.img-field').click()", class: "img-thumbnail img-prev" %>
      </div>
      <div class="col-md-6 pt-3">
        <div class="field">
          <span class="table-head"><%= f.label :title, "◯Title" %></span>
          <br />
          <%= f.text_field :title, size: "40px" %>
        </div>
        <div class="field mt-3">
          <span class="table-head"><%= f.label :email, "◯Country" %></span>
          <br />
          <%= f.text_field :country, size: "40px" %>
        </div>
        <div class="field mt-3">
          <span class="table-head"><%= f.label :text, "◯Text" %></span>
          <br />
          <%= f.text_area :text, size: "55x4" %>
        </div>
        <div class="actions text-right mr-4 mt-4">
          <%= f.submit "更新する", class: "btn btn-success btn-sm px-3" %>
          <%= link_to "削除する", post_delete_confirm_path(@post.id), class: "btn btn-danger btn-sm px-3 ml-4" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="container pb-5">
  <div class="row">
    <%= render "layouts/post_search_form" %>
      <div class="col-md-12">
        <table width="100%">
          <tr>
            <td class="col-md-11"><h2>Posts</h2></td>
            <td class="col-md-1"><p class="new-post">
              <%= link_to new_post_path do %>
                <%= image_tag "add-button.png", size: "40", class: "mt-4" %>
              <% end %>
            </p></td>
          </tr>
        </table>
      </div>
    <%= render "layouts/posts", posts: @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= form_with model: @post, url: posts_path, local: true do |f| %>
    <div class="row">
      <div class="col-md-12 mb-4">
        <h2>New Post</h2>
      </div>
      <div class="col-md-6 image">
        <div class="field">
          <%= f.file_field :image_id, class: "img-field", style: "display:none" %>
        </div>
        <%= image_tag @post.image_id.url, onClick: "$('.img-field').click()", class: "img-thumbnail img-prev" %>
      </div>
      <div class="col-md-6 mt-5 pt-3">
        <p class="flash"><%= flash[:no_post] %></p>
        <table>
          <tr>
            <td><p class="table-head"><%= f.label :title, "Title" %></p></td>
            <td class="col-md-1"></td>
            <td><p><%= f.text_field :title, size: "30" %></p></td>
          </tr>
          <tr>
            <td><p class="table-head"><%= f.label :country, "Country" %></p></td>
            <td></td>
            <td><p><%= f.text_field :country, size: "30" %></p></td>
          </tr>
          <tr>
            <td><p class="table-head mb-5 pb-5"><%= f.label :text, "Text" %></p></td>
            <td></td>
            <td><p><%= f.text_area :text, size: "40x4" %></p></td>
          </tr>
        </table>
        <div class="actions text-right">
          <%= f.submit "投稿する", class: "btn btn-success btn-md" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/search.html.erb
<div class="container">
  <div class="row">
    <%= render "layouts/post_search_form" %>
      <div class="col-md-12">
        <h5>検索結果 "<strong><%= @keyword %></strong>"</h5>
      </div>
    <%= render "layouts/posts", posts: @posts %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mb-3">
      <h2>Post detail</h2>
    </div>
    <div class="col-md-6">
      <%= image_tag @post.image_id.url, class: "img-thumbnail" %><br />
      <i class="fas fa-comment"></i>&thinsp;<%= @post_comments.count %><br />
      <%= render "layouts/favorite", post: @post %>
    </div>
    <div class="col-md-6">
      <table class="mb-3">
        <tr>
          <th><span class="table-head">User</span></th>
          <td class="col-md-1 col-sm-1"></td>
          <td>
            <%= link_to user_path(@user) do %>
            <span class="table-data link">
            <%= @user.name %>
            </span>
            <% end %>
          </td>
        </tr>
        <tr>
          <th><span class="table-head">Title</span></th>
          <td></td>
          <td><span class="table-data"><%= @post.title %></span></td>
        </tr>
        <tr>
          <th><span class="table-head">Country</span></th>
          <td></td>
          <td><span class="table-data"><%= @post.country %></span></td>
        </tr>
        <tr>
          <th><span class="table-head">Text</span></th>
          <td></td>
          <td><span class="table-data"><%= @post.text %></span></td>
        </tr>
      </table>
      <% if @user == current_user %>
        <div class="text-right">
          <%= link_to "編集する", edit_post_path(@post.id), class: "btn btn-primary btn-sm px-3" %>
        </div>
      <% end %>
      <% if @post_comments.count == 0 %>
        <h2>No Comment</h2>
      <% elsif @post_comments.count == 1 %>
        <h2><span class="comment-count">1 </span>Comment</h2>
      <% else %>
        <h2>
          <span class="comment-count">
            <%= @post_comments.count %>
          </span>Comments
        </h2>
      <% end %>
      <p class="flash"><%= flash[:no_comment] %></p>
      <%= form_with model: @post_comment, url: post_post_comments_path(@post.id), local: true do |f| %>
        <div class="field">
          <%= f.text_area :comment, class: "comment-form", size: "58x4" %>
        </div>
        <div class="actions text-right">
          <%= f.submit "コメントする", class: "btn btn-success btn-sm" %>
        </div>
      <% end %>
      <table width="100%">
        <% @post_comments.reverse.each do |post_comment| %>
          <tr>
            <td class="col-md-9">
              <%= link_to user_path(post_comment.user.id) do %>
                <%= image_tag post_comment.user.image_id.url, size: "40" %><br />
              <% end %>
              <span class="name__date">
                <%= post_comment.user.name %>&emsp;
                <%= time_ago_in_words(post_comment.created_at) %>
              </span><br />
              <%= post_comment.comment %>
              <br />
              <br />
            </td>
            <td class="col-md-3">
              <div class="text-right">
                <% if post_comment.user == current_user %>
                  <%= link_to "削除する", post_post_comment_path(post_comment.id, post_comment.post.id), method: :delete, class: "btn btn-danger btn-sm" %>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>