config/routes.rb
Rails.application.routes.draw do

  root "homes#top"
  get "about" => "homes#about"

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  resources :users, except: [:create, :new] do
    get "unsubscribe/:id" => "users#unsubscribe", as: "unsubscribe"
    collection do
      get "search"
    end
  end

  devise_scope :user do
    get "signup" => "users/registrations#new"
    get "login" => "users/sessions#new"
    delete "logout" => "users/sessions#destroy"
    post "guest_sign_in" => "users/sessions#guest_sign_in"
  end

  post 'follow/:id' => 'relationships#follow', as: 'follow'
  delete 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get "followings/:id", :to => "relationships#followings", as: "followings"
  get "followers/:id", :to => "relationships#followers", as: "followers"

  resources :posts do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only:[:create, :destroy]
    get "delete_confirm/:id" => "posts#delete_confirm", as: "delete_confirm"
    collection do
      get "search"
    end
  end
end

app/views/layouts/_center_line.html.erb
<div class="col-md-1 text-center pl-5 ml-3">
  <%= image_tag "center-line.png", width: "3px", height: "420px" %>
</div>

app/views/layouts/_favorite.html.erb
<span id="favorites_buttons_<%= post.id %>">
  <% if post.favorited_by?(current_user) %>
    <%= link_to post_favorites_path(post.id, post.favorites.ids), method: :delete, remote: true, class: "link" do %>
      <i class="fas fa-heart red-heart"></i>
      <%= post.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to post_favorites_path(post.id), method: :post, remote: true, class: "link" do %>
      <i class="fas fa-heart grey-heart"></i>
      <%= post.favorites.count %>
    <% end %>
  <% end %>
</span>

app/views/layouts/_header.html.erb
<header class="mb-5">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/" id="header-logo"><%= image_tag "title-logo.png", size: "70x70", class: "ml-5" %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <div class="flash ml-5 pl-5"><%= flash[:notice] %></div>
        <ul class="navbar-nav ml-auto mr-5">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "MyPage", user_path(current_user.id), class: "nav-link text-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to "Posts", posts_path, class: "nav-link text-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to "Users", users_path, class: "nav-link text-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", logout_path, method: :delete, class: "nav-link text-dark" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "About", about_path, class: "nav-link text-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", login_path, class: "nav-link text-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to "ゲストログイン(閲覧用)", guest_sign_in_path, method: :post, class: "nav-link text-dark" %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", signup_path, class: "nav-link text-dark" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_post_search_form.html.erb
<div class="col-md-12 mt-2 text-right">
  <%= form_with url: search_posts_path, local: true, method: :get do |f| %>
    <div class="field">
      <%= f.text_field :keyword %><%= f.submit "検索", class: "search-button" %>
    </div>
  <% end %>
</div>

app/views/layouts/_posts.html.erb
<div class="col-md-12 mt-1" width="100%">
  <% posts.reverse.each do |post| %>
    <%= link_to post_path(post.id), class: "link post-link" do %>
      <table class="post-list mr-3 mb-3">
        <tr>
          <td><%= image_tag post.image_id.url, size: "250x200" %></td>
        </tr>
        <tr>
          <td>&emsp;
            <%= post.title %>
            <span class="heart-button">
              <%= render partial: "layouts/favorite", locals: { post: post } %>
            </span>
          </td>
        </tr>
      </table>
    <% end %>
  <% end %>
  <div class="col-md-12">
    <%= paginate posts %>
  </div>
</div>

app/views/layouts/_user_search_form.html.erb
<div class="col-md-12 mt-2 text-right">
  <%= form_with url: search_users_path, local: true, method: :get do |f| %>
    <div class="field">
      <%= f.text_field :keyword %><%= f.submit "検索", class: "search-button" %>
    </div>
  <% end %>
</div>

app/views/layouts/_users_left.html.erb
<div class="col-md-5">
  <table>
    <% users.slice(0..7).each do |user| %>
      <tr>
        <td class="col-md-1">
          <%= link_to user_path(user.id), class: "user-link" do %>
          <%= image_tag user.image_id.url, class: "user-image", size: "60x50" %>
          <% end %>
        </td>
        <td></td>
        <td class="col-md-3"><%= user.name %></td>
        <td></td>
        <td class="col-md-3">
          <% unless current_user == user %>
            <% if current_user.following?(user) %>
              <%= link_to "Unfollow", unfollow_path(user.id), method: :delete, class: "btn btn-danger btn-sm no-follow" %>
            <% else %>
              <%= link_to "Follow", follow_path(user.id), method: :post, class: "btn btn-primary btn-sm px-3 yes-follow" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/_users_right.html.erb
<div class="col-md-5">
  <table>
    <% users.slice(8..-1).each do |user| %>
      <tr>
        <td class="col-md-1">
          <%= link_to user_path(user.id) do %>
          <%= image_tag user.image_id.url, class: "user-image", size: "60x50" %>
          <% end %>
        </td>
        <td></td>
        <td class="col-md-3"><%= user.name %></td>
        <td></td>
        <td class="col-md-3">
          <% unless current_user == user %>
            <% if current_user.following?(user) %>
              <%= link_to "Unfollow", unfollow_path(user.id), method: :delete, class: "btn btn-danger btn-sm" %>
            <% else %>
              <%= link_to "Follow", follow_path(user.id), method: :post, class: "btn btn-primary btn-sm px-3" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="col-md-12">
    <%= paginate users %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ituka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>